### ISSUE TITLE
Rewrite Checklist

### ISSUE THREAD

**Issue by avarsh** [avarsh/ape2d#6]
Since the engine is being rewritten/cleaned up, here is a checklist of which features should be present within the rewrite:

## ECS

- [x] Entity creation and deletion
- [x] Component creation, retrieval and deletion
- [x] Component enabling and disabling 
- [x] Entity tagging
- [ ] Blueprints
- [x] Default components
- [ ] Exclusive components

## Core
- [x] 2D Vector
- [x] Transform component
- [x] Rects
- [x] Callback based Events
- [ ] Event Queue
- [ ] Timer or frame counting functionality

## Graphics and Windowing
- [x] SDL based rendering (See: #4)
- [x] Window management
- [ ] Viewports and automatic view scaling

## Scenes
- [ ] Scene graphs with node insertion and removal
- [ ] Transformation cascading 

## Input
- [ ] Reading input from JSON files
- [ ] Space partitioning for mouse input
